name: Release CLI and Docker

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and Release CLI & Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Determine version and prerelease
        id: version_check
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          VERSION="${TAG_NAME#v}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          if [[ "$TAG_NAME" == *"+"* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ steps.version_check.outputs.IS_PRERELEASE }}
          generate_release_notes: true
          files: |
            build/orca-amd64-linux
            build/orca-amd64-windows.exe
            build/orca-amd64-mac-arm
            build/orca-amd64-mac-intel
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Log in to GHCR
        if: steps.version_check.outputs.IS_PRERELEASE == 'false'
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        if: steps.version_check.outputs.IS_PRERELEASE == 'false'
        run: |
          docker build -t ghcr.io/orc-analytics/core:${{ env.VERSION }} \
                       -t ghcr.io/orc-analytics/core:latest \
                       -f ./Dockerfile .

      - name: Push Docker image
        if: steps.version_check.outputs.IS_PRERELEASE == 'false'
        run: |
          docker push ghcr.io/orc-analytics/core:${{ env.VERSION }}
          docker push ghcr.io/orc-analytics/core:latest
